spring.application.name=spring-gift
spring.messages.basename=errors
logging.level.org.springframework.jdbc=debug
spring.h2.console.enabled=true
#h2
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.username=sa
spring.datasource.password=

#my-sql
#spring.datasource.url=jdbc:mysql://localhost:3306/giftdb
#spring.datasource.username=giftuser
#spring.datasource.password=giftpass
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
logging.level.org.hibernate.orm.jdbc.bind=TRACE

kakao.api.key=${KAKAO_API_KEY}
redirect.url=${REDIRECT_URL}
aes.secret.key=${AES_SECRET_KEY}